spring:
  datasource:
    driverClassName: 'org.h2.Driver'
    uri: 'jdbc:h2:mem:rmsapp'
    username: 'sa'
    password: ''
  jpa:
    hibernate:
      ddl-auto: 'create'
      show_sql: false
      format_sql: false
  h2:
    console:
      enabled: true
      path: '/console'
      webAllowOthers: true
server:
  servlet-path: '/v0'